[package]
name = "ngeom"
version = "0.1.0"
edition = "2021"

[dependencies]
ngeom-macros = { path = "../ngeom-macros" }

[features]
default = ["std"]
std = []

[[example]]
name = "physics"
path = "examples/physics.rs"

[dev-dependencies]
kiss3d = "0.35.0"
