[package]
name = "ngeom-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.71"
quote = "1.0.36"
proc-macro2 = "1.0.86"
num-integer = "0.1.46"
nalgebra = "0.33.0"
